### ISSUE TITLE
agent-js: allow multiple fossilizers

### ISSUE THREAD

**Issue by such** [stratumn/indigo-js#10]
Fossilizers would be a priority because people might want to timestamp on different backends.

**Comment by simonvadee** [comment]
BREAKING CHANGES:
 
- an array of `storeHttpClients` will be passed to the process at creation
- an array of `fossilizerHttpClients`  will be passed to the process at creation
- the `callbackUrl` sent to the fossilizers will no longer target the agent, a `POST /insertEvidence` to the store(s) will be used instead. As a consequence, the agent will no longer expose the route `POST /:process/evidence/:linkHash`
- process.GetInfo()'s return value will be updated to include every store/fossilizer

OPEN QUESTIONS: 

- which store should we use for a getSegment/findSegment ? we can either have a notion of primary/secondary stores or return the value stored by each store.
- how do we want to deal with errors returned by stores on saving ? (eg: TMStore fails to save a segment because it couldn't validate the segment schema while dummystore succeeded to save)
- how do we want to use `didFossilize` ? websocket support should be added to fossilizers (cf [this](https://github.com/stratumn/sdk/issues/97)), so we could use a notification mechanism to call `didFossilize` once each fossilizer completed its job.

**Comment by simonvadee** [comment]
I'm opening a new issue for multiple stores support
